### ISSUE TITLE
Add client-side validation on todo creation

### ISSUE THREAD

**Issue by Mthrboard** [ivanolmo/todo-mvc-auth#14]
Right now you can create a todo without entering a due date, but if you do the page won't load afterwards because the due date in the DB is null. Client-side validation will ensure all required fields have been entered properly before attempting to add the record. Also, if there is missing data, the page should flag what's missing so the user can easily see what to add.

**Comment by GooferG** [comment]
What do we mean by "Client-side validation" in this case? Could you clarify? 😊

**Comment by Mthrboard** [comment]
I'm referring to making sure the user has entered something in every input field that's required in the schema. There is a built-in way to do this in the client before data is even sent to the server. https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

We could also update the client-side JavaScript to validate the form data as well, which could include more verbose tests (ex. Making sure the due date is in the future, instead of just making sure a date is entered). These verbose tests might not be absolutely necessary for our app, but we should add something.

**Comment by GooferG** [comment]
Okay, awesome, I can also look into adding that if we want! That would be nice. It always looks clean when you try to fill out a form and get a response saying "field required" or something like that.
