### ISSUE TITLE
Add the ability to edit existing tasks

### ISSUE THREAD

**Issue by Mthrboard** [ivanolmo/todo-mvc-auth#5]
## You should be able to edit an existing task, updating the wording, due date, category. etc (depending on which other features we add)

**Comment by leahthompson01** [comment]
Going to make it a second route, so send you to a separate page to edit and send the put request. Have to edit todo, edit tags, sub tasks, etc. After it will reroute you to todos page with all of them shown. Will only edit that specific task, not the subtasks.

**Comment by leahthompson01** [comment]
Have to figure out the edit for the tags. Probably try to add a trash can for each tag so you can choose which ones to delete or edit
